import torch
import numpy as np

SAMPLE_RATE = 16000
SOUNDSTREAM_N_FFT = 1024
SOUNDSTREAM_WIN_LENGTH = 640

HOP_LENGTH = 320
TRANSCRIPTION_HOP_LENGTH = 512
N_FFT = SOUNDSTREAM_N_FFT
WINDOW_LENGTH_THIS = SOUNDSTREAM_WIN_LENGTH
MEL_FMIN_THIS = 0
N_MELS_THIS = 128
MEL_NORM = np.inf
WINDOW_LENGTH = 2048
N_MELS = 229
MEL_FMIN = 0
MEL_FMAX = SAMPLE_RATE // 2

ONSET_LENGTH = HOP_LENGTH
OFFSET_LENGTH = HOP_LENGTH
HOPS_IN_ONSET = ONSET_LENGTH // HOP_LENGTH
HOPS_IN_OFFSET = OFFSET_LENGTH // HOP_LENGTH
MIN_MIDI = 21
MAX_MIDI = 108
# MAX_MIDI = 127
N_KEYS = MAX_MIDI - MIN_MIDI + 1
DRUM_CHANNEL = 9
DTW_FACTOR = 3

SEQ_LEN = 327680

DEFAULT_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

POP_EM_MAP = [0, 32, 10, 18, 52, 87, 24, 29]


def get_config():
    return {'SAMPLE_RATE': SAMPLE_RATE, 'HOP_LENGTH': HOP_LENGTH, 'N_FFT': N_FFT, 'WINDOW_LENGTH': WINDOW_LENGTH_THIS,
            'N_MELS': N_MELS_THIS, 'MEL_FMIN': MEL_FMIN_THIS, 'MEL_FMAX': MEL_FMAX, 'MEL_NORM': MEL_NORM}